### PR TITLE
Sugarizer integration

### PR DESCRIPTION
**Pull request by llaske**
- Few issues fixed during Sugarizer integration
- Add extensions and medias: not sure to understand why these files are now include. Guess I've clicked on the "Extensions" buttons and it download all files

### CODE REVIEW

**Comment by EmilyOng** [comment]
Thank you!

**Comment by llaske** [comment]
Not sure to understand what you want to remove? Did you try [here](https://dev.sugarizer.org), it seems to work. What you mean by it "cuts the screen"?

**Comment by EmilyOng** [comment]
https://imgur.com/a/apih8

It's missing this portion on the lower right corner.. I removed the css input for text because it probably conflicts with scratch's css and cause this portion to be cut

**Comment by llaske** [comment]
You're right. I wondered why I can't find the 'change background' feature :-)
I've updated on my side.
Another question: do you know how we can change localization? I would like to localize the UI to the current Sugarizer language.

**Pull request merged**
